server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: ${REPO_CONFIG_FILES:https://github.com/jesus0508/configuration-files.git}
          #username: ${GIT_USER:user}
          #password: ${GIT_PWD:s3cr3t}
          search-paths: /{application}
          default-label: "develop"
  security:
    user:
      name: ${CLIENT_USER:user}
      password: ${CLIENT_PWD:s3cr3t}